package com.hippogriff.controllers;

import com.hippogriff.accessmysqldata.Organization;
import com.hippogriff.accessmysqldata.OrganizationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/organizations") // This means URL's start with /demo (after Application path)
public class OrganizationController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private OrganizationRepository organizationRepository;

    @GetMapping(path="/")
    public @ResponseBody Iterable<Organization> getAllOrganizations() {
        // This returns a JSON or XML with the organizations
        return organizationRepository.findAll();
    }

}
